### ISSUE TITLE
Marks are random

### ISSUE THREAD

**Issue by platnub** [DeadlyBossMods/DBM-Vanilla#158]
**Is your feature request related to a problem? Please describe.**
I recently started raid leading, and when I am trying to organise things like the CC's during the Atal'ai Defenders fight, I need to assign CC's to enemies. These enemies automatically get marked by DBM, however it seems these marks are completely random.
In the options they are displayed in a certain order (bottom up in the Raid Target Icon menu), however in practise it's random.
Would be nice if this order of marks was kept for the fight, so I can assign specific marks to enemies, instead of having to tell my raiders an order from 1-5.

**Describe the solution you'd like**
Have the marks be used in the way they are displayed in the options.
![image](https://github.com/DeadlyBossMods/DBM-Vanilla/assets/81484914/5ad22c14-6378-4b03-9b3b-b0980a13c679)

**Comment by MysticalOS** [comment]
it's not random in sense that same ghost always gets same mark. we thought that was better approach than some random index order. sadly GUI doesn't reflect this very well.

**Comment by MysticalOS** [comment]
local iconOrder = {
			[221837] = 1,--Zul'Lor
			[221835] = 2,--Mijan
			[221836] = 3,--Zolo
			[221759] = 4,--Gasher
			[221834] = 5,--Loro
			[221833] = 6--Hukku
		}
that's way it does it

**Comment by platnub** [comment]
Awesome, thanks! Would be nice if this was indeed more clear in the GUI. I have enough information for now. Thanks!

**Comment by platnub** [comment]
Sorry for reopening the issue like this. I was just thinking, it might be better to have the marks being used like they are currently displayed in the GUI. Not having them specific per boss. It will make assigning easier, as there are only 5 CC's that need to go out, and with the current system I would need to assign 6 different marks because it's unsure which boss is fought last.

**Comment by emmericp** [comment]
Having a consistent mapping from icon to boss is better because not all bosses are equally dangerous and not all CCs are equally strong. Usually you would want to use a priest to Shackle Zolo but would be fine with something like hunter traps on a less dangerous boss. Having a consistent icon helps a lot with assignment.

**Comment by platnub** [comment]
Personally I see it differently. This way you would need to assign 6 CC's with one of them not being used.
Regardless of the boss, they should all be CC'd right away and not be broken, and that way they won't be a problem for the raid either.
At the end of the day it's up to you.
