### ISSUE TITLE
LUA error every 2-3 seconds

### ISSUE THREAD

**Issue by Nutrinoff** [DeadlyBossMods/DBM-Vanilla#190]
**Describe the bug**

It happens all the time, about every 3rd second

**Do you have an error log of what happened?**

1110x DBM-Interrupts/Interrupt.lua:34: attempt to call field 'GetSpellInfo' (a nil value)
[string "@DBM-Interrupts/Interrupt.lua"]:34: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1052: in function <DBM-Core/DBM-Core.lua:1039>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1052: in function <DBM-Core/DBM-Core.lua:1039>

Locals:
self = <table> {
 timers = <table> {
 }
 categorySort = <table> {
 }
 SyncThreshold = 8
 modId = "DBM-Interrupts"
 groupSpells = <table> {
 }
 iconRestore = <table> {
 }
 yells = <table> {
 }
 revision = 20240823063645
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "Displays the CDs of interrupts to you (and your raid in some configurations)."
 isTrashMod = false
 inCombat = false
 isDummyMod = false
 groupOptions = <table> {
 }
 SPELL_CAST_SUCCESS = <function> defined @DBM-Interrupts/Interrupt.lua:6
 specwarns = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 optionCategories = <table> {
 }
}
args = <table> {
 spellId = 407799
 destName = "Undying Laborer"
 destGUID = "Creature-0-5211-0-113-210537-00004739BB"
 sourceName = "Teranas"
 destFlags = 2600
 event = "SPELL_CAST_SUCCESS"
 sourceRaidFlags = 0
 spellName = "Seal of Martyrdom"
 destRaidFlags = 0
 timestamp = 1724425872.885000
 sourceFlags = 1304
 sourceGUID = "Player-5825-02234DCE"
}
key = nil
value = nil
Name = "Strangle"
ID_no_taint = 47476
Duration = 60
_ = nil
SpellIcon = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Strangulate = <table> {
 }
 SilencingShot = <table> {
 }
 OpticalBlast = <table> {
 }
 Muzzle = <table> {
 }
 CounterShot = <table> {
 }
 Silence = <table> {
 }
 SolarBeam = <table> {
 }
 Rebuke = <table> {
 }
 Quell = <table> {
 }
 MindFreeze = <table> {
 }
 AvengersShield = <table> {
 }
 Disrupt = <table> {
 }
 SpearHandStrike = <table> {
 }
 Pummel = <table> {
 }
 WindShear = <table> {
 }
 SpellLock = <table> {
 }
 CounterSpell = <table> {
 }
 SkullBash = <table> {
 }
}
(for control) = "Strangulate"
key = "Strangulate"
value = <table> {
 1 = "Strangle"
 2 = 47476
 3 = 60
}
(*temporary) = nil
(*temporary) = 407799
(*temporary) = "attempt to call field 'GetSpellInfo' (a nil value)"

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, because it worked before one of the last few updates, i only noticed it due to the warning of a lot of addon issues so installed bug-grabber because of it

**Which version of DeadlyBossMods are you using?**
DBM-Core-11.0.3

**Was it working in a previous version? If yes, which was the last good one?**
Yes, but i'm not sure which

**Additional context**

**Comment by jungheeMW** [comment]
DBM-Interrupts is a 3rd party addon and not officially supported by DBM.

**Comment by Nutrinoff** [comment]
Ah derp, mb, thanks for quick answer!
