### ISSUE TITLE
Error in frist boss of ZG raid

### ISSUE THREAD

**Issue by HugoBalbino** [DeadlyBossMods/DBM-Vanilla#208]
**Describe the bug**

**Do you have an error log of what happened?**

4x DBM-Core/DBM-Core.lua:6765: attempt to call upvalue 'GetSpellCooldown' (a nil value)
[string "@DBM-Core/DBM-Core.lua"]:6765: in function `GetSpellCooldown'
[string "@DBM-Core/modules/objects/BossMod.lua"]:558: in function `CheckInterruptFilter'
[string "@DBM-Raids-Vanilla/VanillaZG/Jeklik.lua"]:43: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1080: in function <DBM-Core/DBM-Core.lua:1067>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1080: in function <DBM-Core/DBM-Core.lua:1067>

Locals:
Skipped (In Encounter)

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
745

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by emmericp** [comment]
fixed in a core release earlier this week :)
