### ISSUE TITLE
BRD LUA ERROR

### ISSUE THREAD

**Issue by jextercs** [DeadlyBossMods/DBM-Vanilla#240]
**Describe the bug**
Spamming Lua Error in TheSeven encounter in the BRD Anniversary Raid

**Do you have an error log of what happened?**
43x ...ddOns/DBM-Raids-Vanilla/BlackrockDepths/TheSeven.lua:201: attempt to index field '?' (a nil value)
[string "@DBM-Raids-Vanilla/BlackrockDepths/TheSeven.lua"]:201: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1084: in function <DBM-Core/DBM-Core.lua:1071>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1084: in function <DBM-Core/DBM-Core.lua:1071>

Locals:
Skipped (In Encounter)

**Which version of DeadlyBossMods are you using?**
DBM Core 11.0.24
DBM Vanilla r754

**Comment by thebl4ckd0g** [comment]
I get the following LUA error in BRD in the Anniversary event myself:

DBM Core 11.0.24
DBM Vanilla r754

`Message: ...ddOns/DBM-Raids-Vanilla/BlackrockDepths/TheSeven.lua:216: attempt to index field '?' (a nil value)
Time: Thu Oct 24 17:56:55 2024
Count: 2
Stack: ...ddOns/DBM-Raids-Vanilla/BlackrockDepths/TheSeven.lua:216: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/DBM-Raids-Vanilla/BlackrockDepths/TheSeven.lua"]:216: in function `handler'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:1082: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:1069>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:1082: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:1069>

Locals: self = <table> {
 stats = <table> {
 }
 isTrashMod = false
 ignoreBestkill = false
 modId = "DBM-Raids-Vanilla"
 engagedDiffText = "Looking For Raid - "
 revision = 20240916054251
 yells = <table> {
 }
 DefaultOptions = <table> {
 }
 iconRestore = <table> {
 }
 engagedDiffIndex = 17
 isDummyMod = false
 encounterId = 3048
 localization = <table> {
 }
 announces = <table> {
 }
 subTab = 5
 timers = <table> {
 }
 specwarns = <table> {
 }
 instanceId = 1301
 engagedDiffModifier = 0
 modelId = 122582
 engagedDiff = "lfr"
 inCombatOnlyEventsRegistered = 1
 multiMobPullDetection = <table> {
 }
 groupSpells = <table> {
 }
 findFastestComputer = <table> {
 }
 zones = <table> {
 }
 statTypes = "lfr,normal,heroic"
 Options = <table> {
 }
 optionCategories = <table> {
 }
 addon = <table> {
 }
 categorySort = <table> {
 }
 combatInfo = <table> {
 }
 SyncThreshold = 8
 id = "2667"
 groupOptions = <table> {
 }
 creatureId = 226307
 usedIcons = <table> {
 }
 inCombat = true
 vb = <table> {
 }
 inCombatOnlyEvents = <table> {
 }
}
args = <table> {
 spellId = 464334
 destGUID = ""
 sourceName = "Doom'rel"
 destFlags = -2147483648
 event = "SPELL_CAST_START"
 sourceRaidFlags = 0
 spellName = "Summon Felguard"
 destRaidFlags = -2147483648
 timestamp = 1729807014.411000
 sourceFlags = 68168
 sourceGUID = "Creature-0-3779-2792-10207-226310-00001AC0BB"
}
spellId = 464334
(*temporary) = nil
(*temporary) = "Creature-0-3779-2792-10207-226310-00001AC0BB"
(*temporary) = nil
(*temporary) = "Creature-0-3779-2792-10207-226310-00001AC0BB"
(*temporary) = <table> {
 phase1CastTimer = 19.693000
 spellId = 464334
 icon = 136216
 lastCast = 1065022.219000
 option = "Timer464334ai"
 type = "ai"
 simpType = "cd"
 id = "Timer464334ai"
 objClass = "Timer"
 mod = <table> {
 }
 startedTimers = <table> {
 }
 colorType = 4
 name = "Summon Felguard"
 timer = 33
 isPriority = false
 inlineIcon = ""
}
(*temporary) = 33
(*temporary) = false
(*temporary) = "attempt to index field '?' (a nil value)"
timerSunderArmorCD = <table> {
 spellId = 464347
 icon = 132363
 option = "Timer464347ai"
 type = "ai"
 simpType = "cd"
 id = "Timer464347ai"
 objClass = "Timer"
 mod = <table> {
 }
 startedTimers = <table> {
 }
 colorType = 5
 name = "Sunder Armor"
 timer = 33
 isPriority = false
 inlineIcon = ""
}
timerMortalStrikeCD = <table> {
 spellId = 464348
 icon = 132355
 option = "Timer464348ai"
 type = "ai"
 simpType = "cd"
 id = "Timer464348ai"
 objClass = "Timer"
 mod = <table> {
 }
 startedTimers = <table> {
 }
 colorType = 5
 name = "Mortal Strike"
 timer = 33
 isPriority = false
}
timerRendCD = <table> {
 spellId = 464358
 icon = 132155
 option = "Timer464358ai"
 type = "ai"
 simpType = "cd"
 id = "Timer464358ai"
 objClass = "Timer"
 mod = <table> {
 }
 startedTimers = <table> {
 }
 colorType = 3
 name = "Rend"
 timer = 33
 isPriority = false
}
timerRampageCD = <table> {
 spellId = 464359
 icon = 132352
 option = "Timer464359ai"
 type = "ai"
 simpType = "cd"
 id = "Timer464359ai"
 objClass = "Timer"
 mod = <table> {
 }
 startedTimers = <table> {
 }
 colorType = 5
 name = "Rampage"
 timer = 33
 isPriority = false
 inlineIcon = ""
}
specWarnRampage = <table> {
 voiceOptionId = "Voice464359"
 hasVoice = 2
 spellId = 464359
 icon = 132352
 option = "SpecWarn464359defensive"
 objClass = "SpecialWarning"
 text = "Rampage - defensive"
 flash = 1
 combinedcount = 0
 mod = <`

**Comment by MysticalOS** [comment]
This is fixed in alpha version of mod. I just have not done a tag yet due to not being finished with other fixes/additions.

Unfortunately i've had a lot of health issues that have kept me awake at night, averaging 1-3 hours of sleep at most per day and it's left me so low energy i've struggled to complete these modules in a timely manner. Sorry for that. I'll tag a new release that's still incomplete, but at least fixes errors on this boss. Then continue trying to get rest of module done before weekend is over.

**Comment by jextercs** [comment]
Thank you for your quick response. Didnt even know you fixed that in an alpha version so I just opened this to let you know. Thank you for your hard work. Health is THE priority. Hope you sort it out :)

**Comment by MysticalOS** [comment]
Yeah it should have been fixed in https://github.com/DeadlyBossMods/DBM-Vanilla/commit/ef2e4ca2bc0f928c9725ce3c06e5520acd7bec7f

the conditional was backwards. so it was never creating the table reference properly, thus creating nil errors when it then tried to reference table it expected to exist (but didn't)
