### ISSUE TITLE
Black Rock Depths (20y event) transcriptor logs

### ISSUE THREAD

**Issue by linaori** [DeadlyBossMods/DBM-Vanilla#241]
I have only a few logs from this evening, will post more as soon as I have. 

Fights (normal):
- The Seven
- General Angerforge
- Ambassador Flamelash
- Emperor Dagran Thaurissan

[BRD-logs.zip](https://github.com/user-attachments/files/17532020/BRD-logs.zip)

**Comment by jungheeMW** [comment]
Here are my transcripts of BRD Normal from tonight, contains 3 bosses:
- General Angerforge
- Ambassador Flamelash
- Emperor Dagran Thaurissan

[BRD normal.zip](https://github.com/user-attachments/files/17532810/BRD.normal.zip)

**Comment by Molkree** [comment]
LFR Ambassador Flamelash and Emperor Dagran Thaurissan
[Transcriptor.lua.zip](https://github.com/user-attachments/files/17534867/Transcriptor.lua.zip)
Normal Emperor Dagran Thaurissan
[Transcriptor.zip](https://github.com/user-attachments/files/17534868/Transcriptor.zip)

**Comment by MysticalOS** [comment]
you guys keep uploading logs of last bosses only, are you all skipping the earlier ones?

**Comment by jungheeMW** [comment]
In my case, I did the earlier bosses earlier in the week. I do recall at one point that you said Blizzard changed a lot of timers, so I only included bosses done after your announcement.

**Comment by linaori** [comment]
I didn't log the first ones, might do it next week. Currently BRD simply isn't worth the time invested to do it again, so my guild is sticking to normal raiding.

**Comment by jungheeMW** [comment]
New Normal BRD, up to General Angerforge
[normal BRD up to angerforge.zip](https://github.com/user-attachments/files/17566316/normal.BRD.up.to.angerforge.zip)
![WoWScrnShot_103024_124920](https://github.com/user-attachments/assets/926226b0-2956-414c-b453-107a9e6ea904)
![WoWScrnShot_103024_125501](https://github.com/user-attachments/assets/7fff1def-e905-439b-89e5-638daf67c52e)

**Comment by MysticalOS** [comment]
since module is done, any future bugs should just go in new tickets, since this was ticket for completing the module
