### ISSUE TITLE
BRD anniversary - chat window spam

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Vanilla#244]
**Describe the bug**
Bael'Gar - Molten Heart - spams chat window

**Do you have an error log of what happened?**
No log, see screenshot

**Screenshots**
![WoWScrnShot_111324_124328](https://github.com/user-attachments/assets/df5f2515-aaf4-4153-8b3c-2c5b4eceda8f)

**Which version of DeadlyBossMods are you using?**
Vanilla_SOD r759-1 alpha

**Comment by MysticalOS** [comment]
that's new, it wasn't spamming previous weeks.
